### ISSUE TITLE
Uma ideia

### ISSUE THREAD

**Issue by alexandre-mbm** [turicas/braindump#1]
Eu tenho feito parecido com isso, para tentar contornar os problemas que você menciona, mas com anotações mais ricas e um fluxo de trabalho mais prático. Usando dois softwares desktop de acordo com a conveniência, ou o tipo ou a classe (categoria) da informação: Zim e Tomboy.  **Porém**, sem sincronia com GitHub. 

Cheguei a fazer um plugin de export HTML para o Tomboy, que ainda não publiquei por falta de contato com os empacotadores.

Agora, vendo que não fui o único a por em prática uma tentativa de solução para aqueles problemas de gerência de conhecimento, vem a minha mente a ideia de sincronizar Zim e Tomboy em um website Markdown estático, a ser hospedado no GitHub. Talvez eu não faça antes de morrer :) mas quis compartilhar a ideia com você.

Na verdade, eu também tenho coisa num Mediawiki. É o terceiro contorno. Para coisas menos low-end, tem se mostrado a melhor solução. A ideia pendente que tenho para ele é automatizar o backup.

Se uma solução Markdown "viável" pudesse unir meus três contornos, invés de substituí-los, penso que seria o ideal.

**Comment by turicas** [comment]
Obrigado pela dica, @alexandre-mbm! De qualquer forma, ainda prefiro essa solução pois:
- Já uso Git/GitHub/markdown diariamente (não precisaria instalar/aprender nada novo);
- Gosto de como o Git mantém/expõe o histórico de commits (facilita acessar informações no passado) e não curto tanto como os softwares de wiki gerenciam isso;
- Dá para hospedar/publicar gratuitamente no GitHub;
- Qualquer um pode acessar facilmente o conteúdo, basta ter um navegador Web;
- Facilita demais a criação de backups (basta fazer um `clone` e depois fazer um `fetch` para atualizar).

No futuro pretendo colocar o [Jekyll](http://jekyllrb.com/) nesse repositório para facilitar o acesso de quem não é desenvolvedor (assim fica mais fácil eu linkar também para enviar links com um conteúdo interessante por IM, e-mail etc.), já que o GitHub dá suporte a ele através do [GitHub Pages](https://pages.github.com/) -- mas como, por enquanto, o foco não é exatamente em apresentar isso bem para terceiros, ainda não dediquei tempo a essa tarefa.

**Comment by alexandre-mbm** [comment]
Eu não lhe propus o uso de um Mediawiki. Cogito ter conversão periódica e semi-automática dos dados de minhas três — Zim, Tomboy, Mediawiki — para Markdown e versioná-los no Github (tal como você). Um gerador de sites estáticos que chamou muito minha atenção também foi o Nikola.
